# Changes here will be overwritten by Copier
_commit: v3.3.0
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
codeowner_username: '@stkr22'
copyright_license: GPL-3.0
github_repository_name: private-assistant-scene-skill-py
github_username: stkr22
project_description: 'Scene Control Skill for Private Assistant: Enables automated
    and voice-activated scene control within smart home environments.'
project_name: Private Assistant Scene Skill
publish_to_pypi: false
python_package_distribution_name: private-assistant-scene-skill
python_package_import_name: private_assistant_scene_skill
python_package_version: 2.0.1
use_containers: true
