# Changes here will be overwritten by Copier
_commit: 1.1.3
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
copyright_license: GNU General Public License v3.0
project_description: 'Scene Control Skill for Private Assistant: Enables automated
    and voice-activated scene control within smart home environments.'
project_name: Private Assistant Scene Skill
python_package_distribution_name: private-assistant-scene-skill
python_package_import_name: private_assistant_scene_skill
version: 0.1.4
